language: ruby
rvm:
- 2.1

install:
 - sudo pip install html5validator

script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --only-4xx --check-favicon --href-ignore "#" --verbose
- html5validator

# branch whitelist
#branches:
#  only:
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
