# Site settings
title: Scott Webster Mountaineering
email: "scott_webster@ymail.com"
phone: "+44 7775 664 642"
description: > # this means to ignore newlines until "baseurl:"
  Scott Webster is a professional moutaineering instructor with extensive Alpine and Antarctic experience, who offers freelance mountain guiding and climbing.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.scottwebster.co.uk
#url: "http://scottwebster.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

except_separator: "\n\n"

timezone: Europe/London

exclude: ['_templates','README.md','.travis.yml','vendor']
permalink: /exped/:categories/:title

sass:
  style: :compressed

gems:
  - jekyll-sitemap
